version: 1
disable_existing_loggers: true
formatters:
    standard:
        format: "%(asctime)s [%(levelname)s] %(name)s | %(message)s"

handlers:
    file_handler:
        class: logging.FileHandler
        filename: "/tmp/mad_log_%Y%m%dT%H%M%S.log"
        formatter: standard
        level: DEBUG

root:
    level: DEBUG
    handlers: [file_handler]
