
#=====================================================
#      S E N S O R S   C O N F I G U R A T I O N
#=====================================================

sensors-configuration:
  # Configuration for GPS
  gps-configuration: sensors/dummy_gps.yaml

  # Configuration for Accelerometer/Gyroscope
  accelerometer_gyroscope-configuration: sensors/dummy_accel_gyro.yaml

  # Configuration for Sonar (Obstacle Avoidance)
  obstacle-avoidance-configuration: sensors/dummy_sonar.yaml

  # Configuration for Enviromental sensor
  environmental-configuration: sensors/dummy_temp_pressure.yaml

#-------------------------------------------------------------------------------------

