
# PRELOAD action to do

preload:
  wait-at-boot: False
  seconds-to-wait: 10

#-------------------------------------------------------------------------------------

#=====================================================
#      S E N S O R S   C O N F I G U R A T I O N
#=====================================================

sensors-configuration:
  # Configuration for GPS
  gps-configuration: sensors/bn880.yaml

  # Configuration for Accelerometer/Gyroscope
  accelerometer_gyroscope-configuration: sensors/mma845x.yaml

  # Configuration for Sonar (Obstacle Avoidance)
  obstacle-avoidance-configuration: sensors/dummy_sonar.yaml

  # Configuration for Enviromental sensor
  environmental-configuration: sensors/bme280.yaml

#-------------------------------------------------------------------------------------

# ROS Node publisher <---> association with sensors
# Ros rate is in Hz (1 -> second, 2 -> half second)
ros-nodes:
  role_navigation:
    sensor-name: gps
    module-name: madis.ros.generic_mad_publisher
    script-name: ../ros/generic_mad_publisher.py
    ros-rate: 2
    ros-node-name: mad_navigator
    ros-topic-name: navigation

  role_environment:
    sensor-name: environmental
    module-name: madis.ros.generic_mad_publisher
    script-name: ../ros/generic_mad_publisher.py
    ros-rate: 4
    ros-node-name: mad_environmental
    ros-topic-name: environment

  role_stability:
    sensor-name: inclinometer
    module-name: madis.ros.generic_mad_publisher
    script-name: ../ros/generic_mad_publisher.py
    ros-rate: 10
    ros-node-name: mad_stabilizer
    ros-topic-name: stability

  role_obstacles:
    sensor-name: sonar
    module-name: madis.ros.generic_mad_publisher
    script-name: ../ros/generic_mad_publisher.py
    ros-rate: 3
    ros-node-name: mad_obstacles
    ros-topic-name: obstacle
